### ISSUE TITLE
https://datahub.io/ gives 521 (Web server is down) error

### ISSUE THREAD

**Issue by jaklinger** [datopian/frontend#437]
https://datahub.io/ results with `521 web server is down` error.

I can't see anywhere else where I should be raising this issue, so apologies if this is the wrong place (though it is similar to #63 so surely I'm not too far wrong...)

**Comment by zelima** [comment]
@jaklinger thanks for reporting. We are actively working to fix that

**Comment by jaklinger** [comment]
I can see that this is fixed now, closing
