### ISSUE TITLE
Lockfiles in the repo should be deleted

### ISSUE THREAD

**Issue by leomrocha** [datopian/frontend#438]
In the root path of the repository there are two lock files:

- package-lock.json
- yarn.lock

That should not have been added to the commit.

## Acceptance

* [ ] Lock files are deleted
* [ ] Lock files are added to the .gitignore file

**Comment by rufuspollock** [comment]
@leomrocha lock files should be there - but probably only one (yarn or npm). By defualt i think we go with yarn.

**Comment by leomrocha** [comment]
OK, sorry, had to delete them to make the system work on local. I will refuse the PR and mark the issue as will not resolve.

Maybe we can  edit the documentation in the README to clarify that the lockfile had to be used: something like this:

`yarn install --frozen-lock-file # will install exactly what's in yarn.lock without updating it` if not yarn refuses the installation

If you approve I will make the change directly in the README.md file on the github editor
